name: Selenium Grid Tests

on:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
          tar -zxvf allure-2.29.0.tgz
          sudo mv allure-2.29.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Start Selenium Grid (Docker)
        run: |
          docker compose up -d

      - name: Wait for Grid to be ready
        run: |
          for i in {1..10}; do
            curl -s http://localhost:4444/status | grep '"ready": true' && break
            echo "Waiting for Grid..."
            sleep 5
          done

      - name: Run Tests
        run: mvn clean test

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate target/allure-results --clean -o target/allure-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report

      - name: Stop Docker
        if: always()
        run: docker compose down